# Generated by Django 2.1.1 on 2018-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0014_auto_20181024_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_users',
            name='city',
            field=models.CharField(default='asdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.CharField(default='asdf', max_length=15),
        ),
    ]
