# Generated by Django 2.1.1 on 2018-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0015_auto_20181024_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gov_fund',
            name='fund',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='city',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='pincode',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='aadhar_no',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
    ]
