# Generated by Django 2.1.1 on 2018-10-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0016_auto_20181024_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_users',
            name='fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gov_fund',
            name='fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='city',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='pincode',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='aadhar_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
