# Generated by Django 2.1.1 on 2018-10-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0017_auto_20181025_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_users',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
