# Generated by Django 2.1.1 on 2018-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0018_auto_20181026_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='aadhar_no',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
