# Generated by Django 2.1.1 on 2018-10-26 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0019_auto_20181026_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
