# Generated by Django 2.1.1 on 2018-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0020_auto_20181026_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='aadhar_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
